coverage:
  status:
    project:
      default:
        target: 84
        threshold: 0.1
        informational: false
comment:
  require_changes: false
  layout: "reach, diff, flags"
  behavior: default
